# Generated by Django 4.2.30 on 2026-10-03 02:50

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover_alt',
            field=models.CharField(blank=True, help_text='Describe the picture in a few words (helps Google Images and screen readers).', max_length=140, verbose_name='Cover image description'),
        ),
        migrations.AddField(
            model_name='post',
            name='focus_keyword',
            field=models.CharField(blank=True, help_text='The phrase you want this post to rank for. Used by the checklist only; visitors never see it.', max_length=80, verbose_name='Main keyword'),
        ),
        migrations.AddField(
            model_name='post',
            name='noindex',
            field=models.BooleanField(default=False, help_text='Tick to keep this post out of Google search results.', verbose_name='Hide from Google'),
        ),
        migrations.AddField(
            model_name='post',
            name='seo_title',
            field=models.CharField(blank=True, help_text='The blue headline on Google, about 50-60 characters. Leave empty to use the post title.', max_length=70, verbose_name='Google title'),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Story'),
        ),
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.CharField(blank=True, help_text='One or two sentences shown under the title and on the Journal page.', max_length=300, verbose_name='Short summary'),
        ),
        migrations.AlterField(
            model_name='post',
            name='meta_description',
            field=models.CharField(blank=True, help_text='The grey text under the headline on Google, about 120-155 characters.', max_length=160, verbose_name='Google description'),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(blank=True, help_text='Set a future time to schedule the post. Leave empty to publish immediately.', null=True, verbose_name='Publish date and time'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, help_text='The last part of the link, e.g. best-sunset-spots-near-nandi-hills. Filled in from the title; keep it short and include your main keyword.', max_length=220, unique=True, verbose_name='Web address ending'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft (only you can see it)'), ('published', 'Published')], default='draft', max_length=10),
        ),
    ]
