# Generated by Django 4.2.30 on 2026-09-17 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_waiter_and_one_open_per_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upi_id', models.CharField(blank=True, help_text='UPI VPA, e.g. tandem@okicici', max_length=100)),
                ('payee_name', models.CharField(blank=True, default='Tandem', max_length=100)),
                ('qr_image', models.ImageField(blank=True, help_text='Optional: upload a UPI QR photo to auto-fill VPA and payee name.', null=True, upload_to='upi_qr/')),
            ],
            options={
                'verbose_name': 'Restaurant settings',
                'verbose_name_plural': 'Restaurant settings',
            },
        ),
        migrations.AddField(
            model_name='orderitem',
            name='ready_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
