# Generated by Django 4.2.30 on 2026-09-17 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_restaurant_settings_and_ready_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('tea_coffee', 'Tea & Coffee'), ('maggi', 'Maggi'), ('breakfast', 'Sandwiches & Breakfast'), ('starters_veg', 'Starters — Veg'), ('starters_nonveg', 'Starters — Non-Veg'), ('fries', 'Fries & Wedges'), ('rice_noodles_pasta', 'Rice, Noodles & Pasta'), ('beverages', 'Refreshers & Soft Drinks'), ('ice_cream', 'Ice Creams'), ('milkshakes', 'Milkshakes')], max_length=20),
        ),
    ]
