# Generated by Django 4.2.30 on 2026-09-17 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_menu_categories_tandem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('tea_coffee', 'Tea & Coffee'), ('maggi', 'Maggi'), ('breakfast', 'Sandwiches & Breakfast'), ('starters_veg', 'Starters — Veg'), ('starters_nonveg', 'Starters — Non-Veg'), ('fries', 'Fries & Wedges'), ('rice_veg', 'Rice, Noodles & Pasta — Veg'), ('rice_nonveg', 'Rice, Noodles & Pasta — Non-Veg'), ('beverages', 'Refreshers & Soft Drinks'), ('ice_signature', 'Ice Creams — Signature'), ('ice_classic', 'Ice Creams — Classic'), ('milkshakes', 'Milkshakes')], max_length=30),
        ),
    ]
