# Generated by Django 4.2.30 on 2026-10-03 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_discount_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='role',
            field=models.CharField(choices=[('waiter', 'Waiter'), ('chef', 'Chef'), ('admin', 'Admin'), ('blogger', 'Blogger')], max_length=10),
        ),
    ]
